name: Build WebDriverAgentRunner for iOS 16.4.1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3'  # 确保使用支持iOS 16.4.1的Xcode版本

    - name: Install dependencies
      run: |
        brew update
        brew install carthage

    - name: Build WebDriverAgent
      run: |
        carthage bootstrap --platform iOS
        xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -sdk iphoneos -configuration Release archive -archivePath $PWD/build/WebDriverAgent.xcarchive CODE_SIGN_IDENTITY="iPhone Developer" PROVISIONING_PROFILE_SPECIFIER="Your_Provisioning_Profile"

    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath $PWD/build/WebDriverAgent.xcarchive -exportPath $PWD/build -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: WebDriverAgentRunner
        path: build/WebDriverAgent.ipa

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      CERTIFICATE_PRIVATE_KEY: ${{ secrets.CERTIFICATE_PRIVATE_KEY }}
      CERTIFICATE: ${{ secrets.CERTIFICATE }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
